extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: "https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings"
level: warning
scope: heading
match: $sentence
indicators:
  - ":"
exceptions:
  - (?:TODO|HOLD|CANCELLED|DECLINED|KILL|PROJ|INPROGRESS|DONE|RESCHEDULE|BLOCKED).*
