#+title: Emacs Config: Base
#+author: Cash Weaver
#+email: cashbweaver@gmail.com

* Overview

Welcome to my Emacs configuration! I've split my work and personal configuration files as (1) I need slighly different things in my work environment and (2) I depend on private plugins for work which I don't have the rights to publish. The work configuration files build on top of the personal ones.

* Introduction
** Literate Programming

My configuration files use literate programming. As an example of literate programming with =org-mode=, let's generate a throw-away file, =foo.md=. First, we'll add the title:

#+begin_example
,#+begin_src md :tangle foo.md
# Foo
,#+end_src
#+end_example

Notice that I specified the syntax (=md=) and the file to output the content to (=foo.md=). Next, let's add a list of my favorite colors.

#+begin_example
,#+begin_src md :tangle foo.md
1. Orange
1. Blue
1. Red
,#+end_src
#+end_example

Now we can run =org-babel-tangle= to extract the content of these two blocks and create =foo.md=. The newly generated =foo.md= will contain:

#+begin_example
,#+begin_src md
# Foo

1. Orange
1. Blue
1. Red
,#+end_src
#+end_example

** Function and Variable Naming Convention

I prefix all of my own functions and variables with =cashpw/= to prevent any unintentional overlaps.

#+begin_src emacs-lisp
(setq
 cashpw/favorite-color "orange")
#+end_src

"Private" functions and variables -- those I wouldn't indend to be accessed directly -- are prefixed with =cashpw/-= (note the two =-='s).

#+begin_src emacs-lisp
(setq
 cashpw/-secret-color "blue")
#+end_src

Additionally, variables and functions which are in a "library"/group are prefixed with either =cashpw/<library name>-= or =cashpw/<library name>--=, depending on their intended visibility.

#+begin_src emacs-lisp
(setq
 cashpw/colors-favorite "orange"
 cashpw/colors--secret "blue")
#+end_src

* Home Directory

#+name: cashpw/home-dir
#+begin_src emacs-lisp
(require 's)

(defvar cashpw/home-dir-path-personal
  "/home/cashweaver"
  "Path to home directory on my personal machine.")

(defvar cashpw/home-dir-path-work
  "/usr/local/google/home/cashweaver"
  "Path to home directory on my work machine(s).")

(defvar cashpw/home-dir-path-work-cloudtop
  "/usr/local/google/home/cashweaver/is-cloudtop"
  "File that, when present, indicates the current machine is my Cloudtop instance.")

(defun cashpw/is-work-p ()
  "Return true if executed on my work machine."
  (file-directory-p
   cashpw/home-dir-path-work))

(defun cashpw/is-work-cloudtop-p ()
  "Return true if executed on my work machine."
  (file-exists-p
   cashpw/home-dir-path-work-cloudtop))

(defvar cashpw/home-dir-path
  (if (cashpw/is-work-cloudtop-p)
      cashpw/home-dir-path-work
    cashpw/home-dir-path-personal)
  "Path to home directory.")

(defvar cashpw/config-dir-path
  (s-lex-format
   "${cashpw/home-dir-path}/.config")
  "Full path to configuration files.")

(defvar cashpw/emacs-config-dir-path
  (s-lex-format
   "${cashpw/config-dir-path}/doom")
  "Full path to Emacs configuration files.")
#+end_src

#+RESULTS: cashpw/home-dir
: cashpw/emacs-config-dir-path

#+begin_src emacs-lisp :tangle config.el :noweb no-export
<<cashpw/home-dir>>
#+end_src

#+begin_src emacs-lisp :tangle packages.el :noweb no-export
<<cashpw/home-dir>>
#+end_src

* Path to Local Packages

#+begin_src emacs-lisp :tangle packages.el
(defvar cashpw/third-party-path
  (if (cashpw/is-work-p)
      "/usr/local/google/home/cashweaver/third_party"
    "/home/cashweaver/third_party")
  "Path to third-party files.")
#+end_src

* Load Additional Config Files

Configuration files should follow the naming convention =(config|packages)-<type>.el= (eg: =config-personal.el=).

** Personal

#+begin_src emacs-lisp :tangle config.el :noweb no-export
(load (s-lex-format
       "${cashpw/emacs-config-dir-path}/config-personal.el"))
#+end_src

#+begin_src emacs-lisp :tangle packages.el :noweb no-export
(load (s-lex-format
       "${cashpw/emacs-config-dir-path}/packages-personal.el"))
#+end_src

** Work

#+begin_src emacs-lisp :tangle config.el :noweb no-export
(when (cashpw/is-work-cloudtop-p)
  (load (s-lex-format
         "${cashpw/emacs-config-dir-path}/config-work.el")))
#+end_src

#+begin_src emacs-lisp :tangle packages.el :noweb no-export
(when (cashpw/is-work-cloudtop-p)
  (load (s-lex-format
         "${cashpw/emacs-config-dir-path}/packages-work.el")))
#+end_src
