;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE MANUALLY.
;; This file is generated from doom.md. You should make your changes there and
;; this file using org-babel-tangle.

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
; (setq user-full-name "John Doe"
;       user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
; (setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
; (setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
; (setq display-line-numbers-type t)


;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

(setq
 user-full-name "Cash Weaver"
 user-mail-address "cashweaver@google.com")

(setq
 cashweaver-home-dir-home
 "/home/cashweaver"
 cashweaver-home-dir-work
 "/usr/local/google/home/cashweaver")

(defvar
 cashweaver-work-config-dir
 (format
  "%s/%s"
  cashweaver-home-dir-work
  ".config/doom")
 "Full path to work Emacs cofiguration files.")
(defun cashweaver-is-work-p ()
  "Return true if executed on my work machine."
  (file-directory-p cashweaver-work-config-dir))

(setq
 doom-theme 'doom-tomorrow-night
 show-trailing-whitespace t)

(setq
 ;; Use YYYY-MM-DD date format.
 calendar-date-style 'iso)

(defun cashweaver-get-date (&optional date-format offset-days)
  "Return the (offset) date in format."
  (interactive)
  (let ((date-format (or date-format "%Y-%m-%d"))
        (offset-days (or offset-days 0)))
    (shell-command-to-string
     (format "echo -n $(date \"+%s\" --date=\"%d days\")" date-format offset-days))))

(defun cashweaver-todays-date ()
  "Return todays date as YYYY-MM-DD."
  (cashweaver-get-date
   ; date-format
   "%Y-%m-%d"
   ; offset-days
   0))

(defun cashweaver-yesterdays-date ()
  "Return yesterday's date as YYYY-MM-DD."
  (cashweaver-get-date
   ; date-format
   "%Y-%m-%d"
   ; offset-days
   -1))

(use-package! anki-editor
  :config
  (setq
   anki-editor-remove-single-paragraph-tags t
   anki-editor-latex-style 'mathjax))

(defun cashweaver-anki-editor-insert-note ()
  (interactive)
  (with-current-buffer
      (find-file-noselect
       "~/proj/anki-cards/anki.org")
    (point-min)
    (anki-editor-insert-note)))

(use-package! aggressive-indent
  :config
  (add-hook 'emacs-lisp-mode-hook #'aggressive-indent-mode))

(after! gnus-alias
  (setq
   gnus-alias-identity-alist '(("work"
                                ;; Refers to
                                nil
                                "Cash Weaver <cashweaver@google.com>"
                                ;; Organization
                                nil
                                ;; Extra headers
                                nil
                                ;; Body
                                nil "~/.email_signature"))
   gnus-alias-default-identity "work"))

;(use-package! calfw-cal
;  :config
;  (setq
;   ; Start the week on Monday
;   calendar-week-start-day 1))
;
;(use-package! calfw-ical)
;(use-package! calfw-org)
;
;(defun cashweaver-calfw-open ()
;  "Open my calendar"
;  (interactive)
;  (cfw:open-calendar-buffer
;   :contents-sources
;   (list
;    (cfw:org-create-source "Green"))))

(use-package! doct
  :commands (doct))

(use-package! free-keys)

(use-package! gnus-alias
  :config
  (autoload 'gnus-alias-determine-identity "gnus-alias" "" t)
  (gnus-alias-init))

(after! gnus-alias
  (setq
   gnus-alias-identity-alist '(("work"
                                ;; Refers to
                                nil
                                "Cash Weaver <cashweaver@google.com>"
                                ;; Organization
                                nil
                                ;; Extra headers
                                nil
                                ;; Body
                                nil "~/.email_signature"))
   gnus-alias-default-identity "work"))

(use-package! langtool
  :init
  (setq
   langtool-language-tool-server-jar
   "~/third_party/LanguageTool-5.5/languagetool-server.jar"
   ;;langtool-language-tool-jar
   ;;"~/third_party/LanguageTool-5.5/languagetool-commandline.jar"
   )
  :config
  (setq
   langtool-default-language
   "en-US"
   langtool-mother-tongue
   "en"))

(defun cashweaver-notmuch-show-open-or-close-all ()
  "Toggle between showing and hiding all messages in the thread."
  (interactive))

(defun cashweaver-notmuch--search-thread-has-tag-p (match-tag)
  "Whether or not the thread has a tag."
  (interactive)
  (let ((thread-tags (notmuch-search-get-tags)))
    (member match-tag thread-tags)))

(defun cashweaver-notmuch-search-toggle-tag (tag)
  "Toggle the provided tag."
  (interactive)
  (if (member tag (notmuch-search-get-tags))
      (notmuch-search-tag (list (concat "-" tag)))
    (notmuch-search-tag (list (concat "+" tag)))))

(defun cashweaver-notmuch--search-thread-toggle-tag (key)
  "Toggle the specified tag(s)."
  (interactive "k")
  (let ((tags (assoc key cashweaver-notmuch-tag-alist)))
    (apply 'notmuch-search-tag (cdr tags))))

(defun cashweaver-notmuch-search-super-archive (&optional beg end)
  "Super archive the selected thread; based on `notmuch-search-archive-thread'."
  (interactive (notmuch-interactive-region))
  (notmuch-search-tag cashweaver-notmuch-super-archive-tags beg end)
  (when (eq beg end)
    (notmuch-search-next-thread)))

(defun cashweaver-org-notmuch-capture-follow-up-mail()
  "Capture mail to org mode."
  (interactive)
  (org-store-link nil)
  (org-capture nil "ef"))

(after! notmuch
  (setq
   notmuch-wash-wrap-lines-length 100
   notmuch-saved-searches '((:name "inbox"
                             :key "i"
                             :query "tag:inbox")
                            (:name "p0"
                             :key "0"
                             :query "tag:p0")
                            (:name "bugs"
                             :key "b"
                             :query "tag:Bug AND tag:inbox")
                            (:name "bugs (all)"
                             :key "B"
                             :query "tag:Bug")
                            (:name "waiting"
                             :key "w"
                             :query "tag:waiting")
                            (:name "automated"
                             :key "a"
                             :query "tag:Automated AND tag:inbox")
                            (:name "to-read"
                             :key "r"
                             :query "tag:Read!")
                            (:name "sent"
                             :key "s"
                             :query "tag:sent")
                            (:name "drafts"
                             :key "d"
                             :query "tag:draft")
                            (:name "calendar-events"
                             :key "c"
                             :query "tag:Calendar-Events AND tag:inbox")
                            (:name "calendar-events (all)"
                             :key "C"
                             :query "tag:Calendar-Events"))
   +notmuch-home-function (lambda ()
                            (notmuch-search "tag:inbox"))
   notmuch-archive-tags '("-inbox"
                          "-unread")
   notmuch-search-line-faces '(("p0" . '(:foreground "red3"))
                               ("Bug" . '(:foreground "ivory4"))
                               ("waiting" . '(:foreground "orange3"))
                               ("Calendar-Events" . '(:foreground "DeepSkyBlue3"))
                               ("Read!" . '(:foreground "magenta3")))
   ;; Superset of `notmuch-archive-tags' for super archiving.
   cashweaver-notmuch-super-archive-tags (append
                                          notmuch-archive-tags
                                          '("-p0"
                                            "-waiting"
                                            "-Read!")))

  ;; Prevent wrapping at 70 characters in email composition.
  (add-hook! 'message-mode-hook 'turn-off-auto-fill)
  (add-hook! 'message-mode-hook 'visual-line-mode))

(use-package! operate-on-number)

(use-package! org-mime)

(setq
 cashweaver-org-non-archival-filepaths
 '())

(defun cashweaver-org-mode-when-done ()
  "Archive entry when it is marked as done (as defined by `org-done-keywords')."
  (when (org-entry-is-done-p)
    (org-clock-out-if-current)
    (unless (org-get-repeat)
      (unless
          (seq-contains-p
           cashweaver-org-non-archival-filepaths
           buffer-file-name)
        (org-archive-subtree-default)))))

(defun cashweaver-org-mode-when-inprogress ()
  "Handle inprogress ehavior"
  (when (string-equal (org-get-todo-state) "INPROGRESS")
    (org-clock-in)))

(after! org
  :config
  (setq
   org-ellipsis " ▾ "
   org-log-done 'time
   ;; Start the org agenda mini-calendar on Monday.
   calendar-week-start-day 1
   org-priority-highest 0
   org-priority-default 2
   org-priority-lowest 4
   org-hide-leading-stars t
   org-todo-keywords
   '((sequence
      ;; A task that needs doing & is ready to do
      "TODO(t)"
      ;; A project, which usually contains other tasks
      "PROJ(p)"
      ;; A task that is in progress
      "INPROGRESS(i)"
      ;; Something external is holding up this task
      "BLOCKED(b)"
      ;; This task is paused/on hold because of me
      "HOLD(h)"
      "|"
      ;; Task successfully completed
      "DONE(d)"
      ;; Task was moved
      "MOVE(m)"
      ;; Task was cancelled, aborted or is no longer applicable
      "KILL(k)")
     (sequence
      ;; A task that needs doing
      "[ ](T)"
      ;; Task is in progress
      "[-](S)"
      ;; Task is being held up or paused
      "[?](W)"
      "|"
      ;; Task was completed
      "[X](D)"))
   org-todo-keyword-faces
   '(("[-]"  . +org-todo-active)
     ("INPROGRESS" . +org-todo-active)
     ("[?]"  . +org-todo-onhold)
     ("BLKD" . +org-todo-onhold)
     ("HOLD" . +org-todo-onhold)
     ("PROJ" . +org-todo-project))
   org-structure-template-alist
   '(("a" . "export ascii")
     ("c" . "center")
     ("C" . "comment")
     ("e" . "example")
     ("E" . "export")
     ("Eh" . "export html")
     ("El" . "export latex")
     ("q" . "quote")
     ("s" . "src")
     ("se" . "src emacs-lisp")
     ("v" . "verse")))
  (add-hook!
   'org-after-todo-state-change-hook
   'cashweaver-org-mode-when-inprogress)
  (add-hook!
   'org-after-todo-state-change-hook
   'cashweaver-org-mode-when-done))

(after! org-agenda
  (setq
   org-agenda-skip-scheduled-if-deadline-is-shown t
   org-agenda-skip-scheduled-if-done t
   org-agenda-skip-scheduled-if-done t
   org-agenda-skip-deadline-if-done t
   org-agenda-include-deadlines t
   org-agenda-block-separator nil
   org-agenda-compact-blocks t
   org-agenda-start-day nil ;; i.e. today
   org-agenda-span 1
   org-agenda-start-on-weekday nil))

(after! org
  (setq
   org-publish-project-alist
   '(("cashweaver.com"
      :base-directory "~/proj/blog-posts/posts/"
      :base-extension "org"
      :publishing-directory "~/proj/cashweaver.com/content/posts/"
      ;;:publishing-function org-pandoc-publish-to-md
      :publishing-function org-hugo-export-to-md
      :section-numbers t
      :with-toc nil))))

;; Publish org-roam files without using org-publish because org-publish requires a top-level headline.
;; ("roam"
;; :base-directory "~/proj/roam/"
;; :base-extension "org"
;; :publishing-directory "~/proj/cashweaver.com/content/posts/"
;; :publishing-function org-hugo-export-to-md
;; :table-of-contents nil
;; :section-numbers t
;; :with-toc nil))))

(defun cashweaver-org-mode-insert-heading-for-today ()
  "Insert a heading for today's date, with relevant tags."
  (interactive)
  (let* ((today-week-number (cashweaver-get-date "%W"))
         (today-quarter-number (cashweaver-get-date "%q"))
         (today-yyyy-mm-dd (cashweaver-get-date "%Y-%m-%d"))
         (today-weekday-name (cashweaver-get-date "%A")))
    (org-insert-heading-respect-content)
    (insert
     (format "%s %s :week%s:quarter%s:"
             today-yyyy-mm-dd
             today-weekday-name
             today-week-number
             today-quarter-number))))

(defun cashweaver-org-mode-insert-heading-for-this-week ()
  "Insert a heading for this week, with relevant tags."
  (interactive)
  (let* ((today-week-number (cashweaver-get-date "%W"))
         (today-quarter-number (cashweaver-get-date "%q"))
         (today-year (cashweaver-get-date "%Y")))
    (org-insert-heading-respect-content)
    (insert
     (format "%s Week %s :week%s:quarter%s:"
             today-year
             today-week-number
             today-week-number
             today-quarter-number))))

(setq
 cashweaver--schedule-block-day '(:start "07:00" :end "19:00")
 cashweaver--schedule-block-one '(:start "07:00" :end "09:00")
 cashweaver--schedule-block-two '(:start "09:00" :end "11:00")
 cashweaver--schedule-block-three '(:start "14:00" :end "16:00")
 cashweaver--schedule-block-four '(:start "16:00" :end "18:00"))

(defun cashweaver-org-schedule-for-block (block-time &optional date)
  (interactive)
  (let ((start-time (plist-get block-time :start))
        (end-time (plist-get block-time :end))
        (date (or date "today")))
    (org-schedule nil (format "%s %s-%s"
                              date
                              start-time
                              end-time))))

(defun cashweaver-org-schedule-today-from-to (start-time end-time &optional date)
  (interactive)
  (let ((date (or date "today")))
    (org-schedule nil (format "%s %s-%s"
                              date
                              start-time
                              end-time))))

(defun cashweaver-org--schedule-today-at (start-time-as-string)
  "Schedule a task today at the specified time."
  (interactive "sWhen?: ")
  (message start-time-as-string)
  (string-match
   "^\\([1-9]\\|[01][0-9]\\|2[0-3]\\):?\\([0-5][0-9]\\)?$"
   start-time-as-string)
  (let
      ((hour
        (string-to-number
         (or
          (match-string 1 start-time-as-string)
          "0")))
       (minute
        (string-to-number
         (or
          (match-string 2 start-time-as-string)
          "0"))))
    (org-schedule nil (format "today %02d:%02d"
                              hour
                              minute))
    (message (number-to-string hour))
    ))

(defun cashweaver-org--schedule-for (start-time end-time &optional date)
  (let ((date (or date "today")))
    (org-schedule nil (format "%s %s-%s"
                              date
                              start-time
                              end-time))))
    ;(org-schedule nil (format "%s %s-%s"
                              ;date
                              ;start-time
                              ;end-time))))

(defun cashweaver-org--schedule-at-for-minutes (start-minute start-hour duration-in-minutes &optional date)
  (let* ((start-time-in-minutes-since-midnight
         (+ start-minute (* start-hour 60)))
        (end-time-in-minutes-since-midnight
         (+ start-time-in-minutes-since-midnight duration-in-minutes))
        (end-minute (mod end-time-in-minutes-since-midnight 60))
        (end-hour (/ end-time-in-minutes-since-midnight 60))
        (date (or date "today")))
    (org-schedule nil (format "%s %02d:%02d-%02d:%02d"
                              date
                              start-hour
                              start-minute
                              end-hour
                              end-minute))))

(setq
 cashweaver--schedule-pomodoro-one '(:start "09:00" :end "09:50")
 cashweaver--schedule-pomodoro-two '(:start "10:00" :end "10:50")
 cashweaver--schedule-pomodoro-three '(:start "11:00" :end "11:50")
 cashweaver--schedule-pomodoro-four '(:start "12:00" :end "12:50")
 cashweaver--schedule-pomodoro-five '(:start "13:00" :end "13:50")
 cashweaver--schedule-pomodoro-six '(:start "14:00" :end "14:50")
 cashweaver--schedule-pomodoro-seven '(:start "15:00" :end "15:50")
 cashweaver--schedule-pomodoro-eight '(:start "16:00" :end "16:50")
 cashweaver--schedule-pomodoro-nine '(:start "17:00" :end "17:50")
 cashweaver--schedule-pomodoro-ten '(:start "18:00" :end "18:50"))

(defun cashweaver-org-schedule-at-pomodoro (pomodoro-time &optional date)
  (interactive)
  (let ((start-time (plist-get pomodoro-time :start)))
        (date (or date "today")))
    (org-schedule nil (format "%s %s"
                              date
                              start-time)))

(defun cashweaver-org-schedule-in-n-hours (offset-hours &optional date)
  (interactive)
  (let* ((time-list (parse-time-string (current-time-string)))
         (current-hour (nth 2 time-list))
         (current-minute (nth 1 time-list))
         (hour (mod (+ current-hour offset-hours) 24))
         (date (or date "today")))
    (org-schedule nil (format "%s %s:%s"
                              date
                              hour
                              current-minute))))

(defun cashweaver-org-schedule-in-n-workdays (num-days &optional time)
  (interactive)
  (let*
      ((time (or time "09:00"))
       (offset-days))
    (org-schedule
     nil
     (format "%s %s"
             offset-days
             time))))

(defun cashweaver-org-goto-most-recent-timestamp-in-current-buffer ()
  "`goto-char' the most recent timestamp in the buffer"
  (interactive)
  (let ((timestamps
         (cl-sort
          (org-element-map
              (org-element-parse-buffer)
              'timestamp
            (lambda (timestamp)
              `(,(org-element-property :raw-value timestamp) . ,(org-element-property :begin timestamp))))
          'org-time>
          :key 'car)))
    (goto-char
     (cdr
      (pop timestamps)))))

(defun cashweaver-org-mode-set-filetag (value)
  "Add another option; requires at least one option to already be present."
  (message "---")
  (goto-char
   (point-min))
  (if (search-forward-regexp
       "#\\+\\(FILETAGS\\|filetags\\): "
       ;; bound
       nil
       ;; noerror
       t)
      (progn
        (end-of-line)
        (insert (format "%s:" value)))
    (progn
      ;; Add filetags beneath the title; assumes there is a title
      (goto-char
       (point-min))
      (when (search-forward-regexp
          "^#\\+\\(TITLE\\|title\\):")
        (end-of-line)
        (newline)
        (cashweaver-org-mode-insert-option
         "FILETAGS"
         (format ":%s:"
                 value))))))

(defun cashweaver-org-mode-insert-option (option value)
  "Insert an org-mode option (#+OPTION: VALUE)."
  (insert
   (format
    "#+%s: %s\n"
    option
    value)))

(after! org
  (setq
   org-capture-templates
   (doct '(("Anki"
            :keys "a"
            :file "~/proj/anki-cards/anki.org"
            :olp ("Default")
            :note-type (lambda ()
                         (completing-read
                          "Note type: "
                          (sort
                           (anki-editor-note-types)
                           #'string-lessp)))
            :note-type-prop anki-editor-prop-note-type
            :template ("* %?"
                       ":PROPERTIES:"
                       ":ANKI_NOTE_TYPE: %{note-type}"
                       ":END:")
            :hook (lambda ()
                    (let* ((note-type
                            (org-entry-get
                             (point)
                             anki-editor-prop-note-type))
                           (fields
                            (anki-editor-api-call-result
                             'modelFieldNames
                             :modelName note-type))
                           ;; Ignore the first field.
                           ;; We'll set it as the title for the subtree.
                           (first-field
                            (pop fields))
                           (second-field
                            (pop fields)))
                      (org-insert-subheading nil)
                      (insert second-field)
                      (dolist (field fields)
                        (org-insert-heading nil)
                        (insert field))
                      (outline-up-heading 1)
                      (evil-org-append-line 1))))))))

(defun cashweaver-org-noter-insert-selected-text-inside-note-content ()
  "Insert selected text in org-noter note.

Reference: https://github.com/weirdNox/org-noter/issues/88#issuecomment-700346146"
  (interactive)
  (progn
    (setq currenb (buffer-name))
    (org-noter-insert-precise-note)
    (set-buffer currenb)
    (org-noter-insert-note)))

(use-package! ol-notmuch
  :after org)

(defun cashweaver-org-roam--get-filetags (&optional node-id)
  "Return a list of all tags used in roam.

Optionally: Exclude tags currently in use in the provided NODE-ID."
  (if node-id
      (org-roam-db-query
       [:select :distinct [tag]
        :from tags
        :where tag :not-in [:select tag
                            :from tags
                            :where (= node_id $s1)]]
       node-id)
    (org-roam-db-query
     [:select :distinct tag
      :from tags])))

(defun cashweaver-org-roam--set-filetag (&optional node-id)
  "Add a filetag in the current file."
  (let ((tag
         (completing-read
          "Select tag: "
          (cashweaver-org-roam--get-filetags node-id)
          )))
    (cashweaver-org-mode-set-filetag tag)))

;;(org-roam-db-query "SELECT DISTINCT tag FROM tags;")
;; "007bbe54-0e36-4af5-b2ec-cf7762299a1f"

;; (let ((current-file-id "6a214828-bea5-47be-bac7-0f0235b0ff3c"))
;;   (org-roam-db-query
;;    [:select :distinct [tag]
;;     :from tags
;;     :where (= node_id $s1)]
;;    current-file-id))

;; (let ((current-file-id "6a214828-bea5-47be-bac7-0f0235b0ff3c"))
;;   (org-roam-db-query
;;    (format
;;     ;; "SELECT DISTINCT tag
;;     ;; FROM tags
;;     ;; WHERE NOT IN (
;;     ;; SELECT tag
;;     ;; FROM tags
;;     ;; WHERE node_id = '\"%s\"'
;;     ;; )"
;;     "SELECT DISTINCT tag
;; FROM tags
;; WHERE node_id = '\"%s\"'"
;;     current-file-id)))
;; (let ((current-file-id "6a214828-bea5-47be-bac7-0f0235b0ff3c"))
;;   (org-roam-db-query
;;    [:select :distinct [tag]
;;     :from tags
;;     :where tag :not-in [:select tag
;;                         :from tags
;;                         :where (= node_id $s1)]]
;;    current-file-id))

(defun cashweaver-org-roam-make-filepath (title &optional time time-zone)
  "Return a filenaem for an org-roam node.

Reference: https://ag91.github.io/blog/2020/11/12/write-org-roam-notes-via-elisp"
  (let ((slug
         (org-roam-node-slug
          (org-roam-node-create
           :title title))))
    (format
     "%s/%s.org"
     org-roam-directory
     slug)))

(defun cashweaver-org-mode-add-option (option value)
  "Add another option; requires at least one option to already be present.

TODO: move to org-mode section"
  (goto-char
   (point-max))
  (insert "foo")
  (when (search-backward-regexp
         "#\\+[A-Za-z_]+:"
         ;; bound
         nil
         ;; noerror
         t)
    (cashweaver-org-mode-insert-option
     option
     value)))

(defun cashweaver-org-mode-insert-option (option value)
  "Insert an org-mode option (#+OPTION: VALUE).

TODO: move to org-mode section"
  (insert
   (format
    "#+%s: %s\n"
    option
    value)))

(defun cashweaver-org-mode-insert-options (options)
  "Insert an alist of org-mode options (#+OPTION: VALUE)."
  (cl-loop for (option . value) in options
           do (cashweaver-org-mode-insert-option
               option
               value)))

(defun cashweaver-org-mode-insert-property (property value)
  "Insert an org-mode property (:PROPERTY: VALUE)."
  (insert
   (format
    ":%s: %s\n"
    property
    value)))

(defun cashweaver-org-mode-insert-properties (properties)
  "Insert an alist of org-mode properties (:PROPERTY: VALUE).

When WRAP is non-nil: Wrap the properties with :PROPERTIES:/:END:."
  (interactive)
  (cl-loop for (property . value) in properties
           do (org-set-property
               property
               value)))

(defun cashweaver-org-roam-new-node (file-path title &optional properties)
  "Build a new org-roam node in a temp file.

PROPERTIES is expected to be an alist of additional properties to include.

Reference: https://ag91.github.io/blog/2020/11/12/write-org-roam-notes-via-elisp"
  (let* ((id
          (org-id-new))
         (dir
          (format
           "%s/%s"
           cashweaver-org-roam-attachment-base-path
           id))
         (created-date
          (cashweaver-get-date
           "[%Y-%m-%d %a %H:%M]"))
         (all-properties
          (append
           `(("ID" . ,id)
             ("DIR" . ,dir))
           properties)))
    (with-temp-file
        file-path
      (cashweaver-org-mode-insert-properties
       all-properties)
      (goto-char
       (point-max))
      (cashweaver-org-mode-insert-options
       `(("TITLE" . ,title)
         ("STARTUP" . "overview")
         ("AUTHOR" . "Cash Weaver")
         ("DATE" . ,created-date)
         ("HUGO_AUTO_SET_LASTMOD" . "t")))
      (org-insert-heading)
      (insert
       "Summary")
      (org-insert-heading)
      (insert
       "Notes")
      (org-insert-heading)
      (insert
       "Thoughts"))))

(defun cashweaver-org-roam-new-node-from-link-heading-at-point (&optional mark-as-done)
  "Build a new org-roam node from the link heading at point."
  (interactive)
  (let* ((link
          (org-element-context))
         (type
          (org-element-property
           :type
           link))
         (url
          (org-element-property
           :raw-link
           link))
         (description
          (cashweaver-org-mode-get-description-from-link-at-point))
         (org-roam-node-file-path
          (cashweaver-org-roam-make-filepath description)))
    ;; TODO Replace with regexp?
    (unless (or (string= type "http")
                (string= type "https")))
    (cashweaver-org-roam-new-node
     org-roam-node-file-path
     description
     `(("ROAM_REFS" . ,url)))
    (if mark-as-done
        (org-todo "DONE"))
    (find-file
     org-roam-node-file-path)))

(defun cashweaver-org-mode-get-description-from-link-at-point ()
  "Reference: https://emacs.stackexchange.com/a/38297"
  (interactive)
  (let ((link
         (org-element-context)))
    (message
     "%s"
     (buffer-substring-no-properties
      (org-element-property
       :contents-begin
       link)
      (org-element-property
       :contents-end
       link)))))

(defun cashweaver-org-roam-open-ref ()
  "Open the ROAM_REF."
  (interactive)
  (let ((roam-refs
         (org-entry-get
          (point)
          "ROAM_REFS")))
    (if (s-starts-with-p
         "http"
         roam-refs)
        (browse-url roam-refs)
      (message
       "Not an http(s) ref (%s)"
       roam-refs))))

;; TODO Consolidate this and the bit in `cashweaver-org-roam-new-node'
(defun cashweaver-org-roam-insert-attachment-path ()
  (let ((dir
         (format
          "%s/%s"
          cashweaver-org-roam-attachment-base-path
          (org-id-get))))
    (save-excursion
      (org-set-property
       "DIR"
       dir))))



(defun cashweaver-org-roam--mirror-roam-refs-to-front-matter ()
  "Copy the list of ROAM_REFS into hugo_custom_front_matter."
  (when (org-roam-file-p)
    (when-let*
        ((keyword
          "HUGO_CUSTOM_FRONT_MATTER")
         (raw-roam-refs
          (org-export-get-node-property
           :ROAM_REFS
           (org-element-parse-buffer)))
         (refs
          (split-string
           raw-roam-refs
           " +"))
         (roam-refs
          (format
           "roam_refs '(%s)"
           (string-join
            (mapcar
             (lambda (ref)
               (format "\"%s\"" ref))
             refs)
            " ")))
         (current-roam-refs
          (or
           (org-roam-get-keyword
            keyword)
           "")))
      (if (not (string=
                roam-refs
                current-roam-refs))
          (org-roam-set-keyword
           (downcase keyword)
           roam-refs)))))

;; Override
;;
;; 1. Export even on first save from org-capture.
;; 2. Make roam files known to org exporter.
;; 3. Mirror ROAM_REFS to hugo_custom_front_matter
(defun org-hugo-export-wim-to-md-after-save ()
  "See `org-hugo-export-wim-to-md-after-save'."
  (interactive)
  (when (not
         (or
          (string=
           (buffer-file-name)
           "/home/cashweaver/proj/roam/unread.org")
          (string=
           (buffer-file-name)
           "/home/cashweaver/proj/roam/unread.org_archive")))
    (let ((org-id-extra-files
           (org-roam-list-files)))
      (org-hugo-export-wim-to-md))))

(add-hook!
 'before-save-hook
 #'cashweaver-org-roam--mirror-roam-refs-to-front-matter)

(use-package! org-roam
  :after org
  :config
  (setq
   org-roam-directory (file-truename
                       "~/proj/roam")
   cashweaver-org-roam-attachment-base-path (file-truename
                                             (format
                                              "%s/attachments"
                                              org-roam-directory))
   org-roam-capture-templates `(("d" "default" plain "%?" :target
                                 (file+head
                                  "${slug}.org"
                                  ,(concat
                                    "#+title: ${title}\n"
                                    "#+author: Cash Weaver\n"
                                    "#+date: [%<%Y-%m-%d %a %H:%M>]\n"
                                    "#+startup: overview\n"
                                    "#+hugo_auto_set_lastmod: t\n"
                                    "\n\n"))
                                 :unnarrowed t)))
  (add-hook! 'org-roam-capture-new-node-hook
             'cashweaver-org-roam-insert-attachment-path)
  (org-roam-db-autosync-mode))

(defun cashweaver-org-roam-set-filetag ()
  "Add a filetag to the current roam file."
  (interactive))

(defun run-function-in-file (filepath function &optional arguments)
  (let ((args (or arguments
                  nil)))
    (save-excursion
      (find-file filepath)
      (apply function arguments)
      (write-file filepath)
      (kill-buffer (current-buffer)))))

(defun cashweaver-org-hugo-export-wim-to-md ()
  (org-hugo-export-wim-to-md-after-save))

(defun cashweaver-org-hugo-export-all (directory)
  (mapc (lambda (filepath)
          (run-function-in-file
           filepath
           'cashweaver-org-hugo-export-wim-to-md))
        (directory-files
         directory
         ;; full
         t
         ;; match
         ".org$")))

;;(cashweaver-org-hugo-export-all
 ;;"/home/cashweaver/proj/roam")

(use-package! ox-pandoc
  :after (:all org)
  :config
  (setq
   org-pandoc-menu-entry
   '((?D "to docx and open." org-pandoc-export-to-docx-and-open)
     (?d "to docx." org-pandoc-export-to-docx)
     (?m "to markdown." org-pandoc-export-to-markdown)
     (?M "to markdown and open." org-pandoc-export-to-markdown-and-open)))
  (when (cashweaver-is-work-p)
    (setq
     org-pandoc-options-for-docx
     '((lua-filter . "/usr/local/google/home/cashweaver/third_party/google_docs_pandoc/pandoc/GenericDocFilter.lua")
       (reference-doc . "/usr/local/google/home/cashweaver/third_party/google_docs_pandoc/pandoc/CashWeaverGenericDocTemplate.docx")
       ;;(reference-doc . "/usr/local/google/home/cashweaver/third_party/google_docs_pandoc/pandoc/GenericDocTemplate.docx")
       (highlight-style . "/usr/local/google/home/cashweaver/third_party/google_docs_pandoc/pandoc/Kodify.theme")))
    ;;(add-hook! 'org-pandoc-after-processing-markdown-hook
    ;;'cashweaver-remove-yaml-header)
    ))

(defun cashweaver-remove-yaml-header ()
  "Remove the 'front matter'/YAML header content from the current buffer."
  (goto-char (point-min))
  (replace-regexp
   "---\\(.\\|\n\\)*---"
   "")
  (goto-char (point-min))
  (delete-blank-lines)
  (delete-blank-lines))

(defun org-pandoc-publish-to (format plist filename pub-dir &optional remove-yaml-header)
  "Publish using Pandoc (https://github.com/kawabata/ox-pandoc/issues/18#issuecomment-262979338)."
  (setq
   org-pandoc-format format
   org-pandoc-option-table (make-hash-table))
  (let ((tempfile
         (org-publish-org-to
          'pandoc filename (concat (make-temp-name ".tmp") ".org") plist pub-dir))
        (outfile (format "%s.%s"
                         (concat
                          pub-dir
                          (file-name-sans-extension (file-name-nondirectory filename)))
                         (assoc-default format org-pandoc-extensions))))
    (org-pandoc-put-options (org-pandoc-plist-to-alist plist))
    (let ((process
           (org-pandoc-run tempfile outfile format 'org-pandoc-sentinel
                           org-pandoc-option-table))
          (local-hook-symbol
           (intern (format "org-pandoc-after-processing-%s-hook" format))))
      (process-put process 'files (list tempfile))
      (process-put process 'output-file outfile)
      (process-put process 'local-hook-symbol local-hook-symbol))))

(defun org-pandoc-pan-to-pub (o)
  (intern
   (format ":org-pandoc-%s" o)))

(defun org-pandoc-pub-to-pan (o)
  (intern
   (substring (symbol-name o) 12)))

(defconst org-pandoc-publish-options
  (mapcar
   'org-pandoc-pan-to-pub
   (append
    org-pandoc-valid-options
    org-pandoc-colon-separated-options
    org-pandoc-file-options)))

(defun org-pandoc-plist-to-alist (plist)
  (let ((alist '()))
    (while plist
      (let ((p (car plist))
            (v (cadr plist)))
        (when (member p org-pandoc-publish-options)
          (add-to-list 'alist (cons (org-pandoc-pub-to-pan p) v))))
      (setq plist (cddr plist)))
    alist))

(defun org-pandoc-publish-to-md (plist filename pub-dir)
  "Publish to markdown using Pandoc."
  ;;(org-pandoc-publish-to 'markdown plist filename pub-dir t))
  (org-pandoc-publish-to 'markdown plist filename pub-dir t))

(defun org-pandoc-publish-to-plain (plist filename pub-dir)
  "Publish to markdown using Pandoc."
  (org-pandoc-publish-to 'plain plist filename pub-dir))

(use-package! pdf-tools
  :config
  (pdf-tools-install))

(setq
 alert-fade-time 60
 alert-default-style 'libnotify)

(defun cashweaver-org-hugo--export-all-roam ()
  "Export all roam nodes."
  (interactive)
  ;; TODO
  )

(defun cashweaver-org-mode--split-tags-to-list (tags-as-string)
  "Strip the wrapping ':' from TAG; if present."
  (if tags-as-string
      (if (string-match
           "^:\\(.*\\):$"
           tags-as-string)
          (split-string
           (match-string 1 tags-as-string)
           ":")
        nil)
    nil))

(defun cashweaver-org-hugo--tag-processing-fn-roam-tags (tag-list info)
  "Add tags from filetags to tag-list for org-roam to ox-hugo compatibility.

Reference: https://sidhartharya.me/exporting-org-roam-notes-to-hugo/#goal

See `org-hugo-tag-processing-functions'."
  (if (org-roam-file-p)
      (let* ((filetags
              (car
               (cdr
                (assoc-string
                 "FILETAGS"
                 (org-collect-keywords
                  '("FILETAGS"))))))
             (filetag-list
              (or
               (cashweaver-org-mode--split-tags-to-list
                filetags)
               '())))
        (append tag-list
                (mapcar
                 #'downcase
                 filetag-list)))
    tag-list))

(use-package! ox-hugo
  :after ox
  :config
  (setq
   org-hugo-allow-spaces-in-tags nil)
  (add-to-list
   'org-hugo-tag-processing-functions
   'cashweaver-org-hugo--tag-processing-fn-roam-tags))

(use-package! org-wild-notifier
  :config
  (setq
   org-wild-notifier-alert-time '(10 2))
  (org-wild-notifier-mode))

(after! writegood-mode
  (setq
   writeroom-width 10))

(use-package! svg-tag-mode
  :config
  (setq
   svg-tag-tags '(("\\(:[A-Z]+:\\)" . ((lambda (tag) (svg-tag-make tag :beg 1 :end -1)))))))

(use-package! org-download)

(use-package! ol-doi)

(defun cashweaver-send-mail-function ())

(defun cashweaver-mail-htmlize-and-send-org-mail ()
  "Converts an org-mode message to HTML and sends."
  (message-mode))

(defun cashweaver-compose-mail-org ()
  (interactive)
  (compose-mail)
  (message-goto-body)
  (setq *compose-html-org* t)
  (org-mode))

(defun cashweaver-mail-toggle-org-message-mode ()
  (interactive)
  (if (derived-mode-p 'message-mode)
      (progn
        (setq *compose-html-org* t)
        (org-mode)
        (message "enabled org-mode"))
    (progn
      (setq *compose-html-org* nil)
      (notmuch-message-mode)
      (message "enabled notmuch-message-mode"))))

(defun cashweaver-htmlize-and-send-mail-org ()
  (interactive)
  (when *compose-html-org*
    (setq *compose-html-org* nil)
    (message-mode)
    (org-mime-htmlize)
    (message-send-and-exit)))

(setq
 send-mail-function #'google-sendgmr-send-it
 message-send-mail-function #'google-sendgmr-send-it)

; Reference; https://www.emacswiki.org/emacs/DocumentingKeyBindingToLambda
(defun evil-lambda-key (mode keymap key def)
  "Wrap `evil-define-key' to provide documentation."
  (set 'sym (make-symbol (documentation def)))
  (fset sym def)
  (evil-define-key mode keymap key sym))

(map!
 ;; Keep in alphabetical order.
 (:leader
  :desc "at point" :n "h h" #'helpful-at-point
  :desc "Store email link" :n "n L" #'org-notmuch-store-link
  :desc "Langtool" :n "t L" #'langtool-check
  (:prefix ("n")
   (:prefix ("A" . "Anki")
    :n "n" #'anki-editor-insert-note))))

(map!
 ;; Keep in alphabetical order.
 :map global-map
 "M-N" #'operate-on-number-at-point)

(after! org
  ;; Keep in alphabetical order.
  (map!
   :map org-mode-map
   :localleader
   (:prefix ("b")
    :n "RET" #'org-table-copy-down)

   (:prefix ("d")
    (:prefix ("h" . "insert heading")
     :n "d" #'cashweaver-org-mode-insert-heading-for-today
     :n "w" #'cashweaver-org-mode-insert-heading-for-this-week)
    (:prefix ("S")
     (:prefix ("." . "today")
      :desc "at" :n "a" #'cashweaver-org--schedule-today-at)
     (:prefix ("h" . "hour")
      (:prefix ("0" . "0?:??")
       :desc "00:00" :n "0" (cmd! (cashweaver-org-schedule-today-from-to "00:00" "00:45"))
       :desc "01:00" :n "1" (cmd! (cashweaver-org-schedule-today-from-to "01:00" "01:45"))
       :desc "02:00" :n "2" (cmd! (cashweaver-org-schedule-today-from-to "02:00" "02:45"))
       :desc "03:00" :n "3" (cmd! (cashweaver-org-schedule-today-from-to "03:00" "03:45"))
       :desc "04:00" :n "4" (cmd! (cashweaver-org-schedule-today-from-to "04:00" "04:45"))
       :desc "05:00" :n "5" (cmd! (cashweaver-org-schedule-today-from-to "05:00" "05:45"))
       :desc "06:00" :n "6" (cmd! (cashweaver-org-schedule-today-from-to "06:00" "06:45"))
       :desc "07:00" :n "7" (cmd! (cashweaver-org-schedule-today-from-to "07:00" "07:45"))
       :desc "08:00" :n "8" (cmd! (cashweaver-org-schedule-today-from-to "08:00" "08:45"))
       :desc "09:00" :n "9" (cmd! (cashweaver-org-schedule-today-from-to "09:00" "09:45")))
      (:prefix ("1" . "1?:??")
       :desc "01:00" :n "RET" (cmd! (cashweaver-org-schedule-today-from-to "01:00" "01:45"))
       :desc "10:00" :n "0" (cmd! (cashweaver-org-schedule-today-from-to "10:00" "10:45"))
       :desc "11:00" :n "1" (cmd! (cashweaver-org-schedule-today-from-to "11:00" "11:45"))
       :desc "12:00" :n "2" (cmd! (cashweaver-org-schedule-today-from-to "12:00" "12:45"))
       :desc "13:00" :n "3" (cmd! (cashweaver-org-schedule-today-from-to "13:00" "13:45"))
       :desc "14:00" :n "4" (cmd! (cashweaver-org-schedule-today-from-to "14:00" "14:45"))
       :desc "15:00" :n "5" (cmd! (cashweaver-org-schedule-today-from-to "15:00" "15:45"))
       :desc "16:00" :n "6" (cmd! (cashweaver-org-schedule-today-from-to "16:00" "16:45"))
       :desc "17:00" :n "7" (cmd! (cashweaver-org-schedule-today-from-to "17:00" "17:45"))
       :desc "18:00" :n "8" (cmd! (cashweaver-org-schedule-today-from-to "18:00" "18:45"))
       :desc "19:00" :n "9" (cmd! (cashweaver-org-schedule-today-from-to "19:00" "19:45")))
      (:prefix ("2" . "2?:??")
       :desc "20:00" :n "0" (cmd! (cashweaver-org-schedule-today-from-to "20:00" "20:45"))
       :desc "21:00" :n "3" (cmd! (cashweaver-org-schedule-today-from-to "21:00" "21:45"))
       :desc "22:00" :n "2" (cmd! (cashweaver-org-schedule-today-from-to "22:00" "22:45"))
       :desc "23:00" :n "3" (cmd! (cashweaver-org-schedule-today-from-to "23:00" "23:45")))
      :desc "03:00" :n "3" (cmd! (cashweaver-org-schedule-today-from-to "03:00" "03:45"))
      :desc "04:00" :n "4" (cmd! (cashweaver-org-schedule-today-from-to "04:00" "04:45"))
      :desc "05:00" :n "5" (cmd! (cashweaver-org-schedule-today-from-to "05:00" "05:45"))
      :desc "06:00" :n "6" (cmd! (cashweaver-org-schedule-today-from-to "06:00" "06:45"))
      :desc "07:00" :n "7" (cmd! (cashweaver-org-schedule-today-from-to "07:00" "07:45"))
      :desc "08:00" :n "8" (cmd! (cashweaver-org-schedule-today-from-to "08:00" "08:45"))
      :desc "09:00" :n "9" (cmd! (cashweaver-org-schedule-today-from-to "09:00" "09:45")))))
   (:prefix ("M" . "Mail")
    :desc "switch to message-mode" :n "t" #'cashweaver-mail-toggle-org-message-mode)

   (:prefix ("m" . "org-roam")
    :desc "Open ref" :n "O" #'cashweaver-org-roam-open-ref
    :desc "Tag" :n "q" (cmd! ()
                             (when (org-roam-file-p)
                               (let ((node-id (org-roam-node-id
                                               (org-roam-node-at-point))))

                                 (cashweaver-org-roam--set-filetag
                                  node-id)
                                 )))
    ;;#'cashweaver-org-roam--set-filetag
    :desc "Create node from headline link" :n "N" (cmd! ()
                                                        (cashweaver-org-roam-new-node-from-link-heading-at-point
                                                         ;; mark-as-done
                                                         t))
    :desc "Publish all" :n "p" #'cashweaver-org-hugo-export-all)
   (:prefix ("S" . "Structure")
    :n "i" #'org-insert-structure-template)))

(after! notmuch
  ;; Keep in alphabetical order.
  (map!
   :map notmuch-message-mode-map
   :localleader

   "M t" #'cashweaver-mail-toggle-org-message-mode)

  (map!
   :map notmuch-show-mode-map

   "M-RET" #'cashweaver-notmuch-show-open-or-close-all)

  ;; Reply-all should be the default.
  (evil-define-key 'normal notmuch-show-mode-map "cr" 'notmuch-show-reply)
  (evil-define-key 'normal notmuch-show-mode-map "cR" 'notmuch-show-reply-sender)

  ;; Easy archive for my most-used tags.
  (evil-define-key 'normal notmuch-search-mode-map "A" 'notmuch-search-archive-thread)
  (evil-define-key 'normal notmuch-search-mode-map "a" 'cashweaver-notmuch-search-super-archive)
  (evil-define-key 'visual notmuch-search-mode-map "a" 'cashweaver-notmuch-search-super-archive)

  ;; Unbind "t", and re-bind it to "T", so we can set it up as a prefix.
  (evil-define-key 'normal notmuch-search-mode-map "t" nil)
  (evil-define-key 'normal notmuch-search-mode-map "T" 'notmuch-search-filter-by-tag)

  ;; Helpers for toggling often-used tags.
  (evil-lambda-key 'normal notmuch-search-mode-map "t0" '(lambda ()
                                                           "Toggle p0"
                                                           (interactive)
                                                           (cashweaver-notmuch-search-toggle-tag "p0")))
  (evil-lambda-key 'normal notmuch-search-mode-map "tr" '(lambda ()
                                                           "Toggle Read!"
                                                           (interactive)
                                                           (cashweaver-notmuch-search-toggle-tag "Read!")))
  (evil-lambda-key 'normal notmuch-search-mode-map "tw" '(lambda ()
                                                           "Toggle waiting"
                                                           (interactive)
                                                           (cashweaver-notmuch-search-toggle-tag "waiting"))))

(after! org-noter
  (map!
   :map pdf-view-mode-map
   :localleader

   :n "n" #'org-noter-insert-note
   :n "N" #'org-noter-insert-precise-note
   :desc "Quote (precise)" :n "Q" #'cashweaver-org-noter-insert-selected-text-inside-note-content))

(if (cashweaver-is-work-p)
    (load (concat cashweaver-work-config-dir "/config-work.el")))
