[theme]
background = "#1D1F21"
primary = "#C5C8C6"
secondary = "#C5C8C6"
title = "#C5C8C6"
playing = "#DE935F"
playing_selected = "#DE935F"
playing_bg = "#1D1F21"
highlight = "#C5C8C6"
highlight_bg = "#282A2E"
error = "#FFFFFF"
error_bg = "#CC6666"
statusbar = "#C5C8C6"
statusbar_progress = "#DE935F"
statusbar_bg = "#1D1F21"
cmdline = "#C5C8C6"
cmdline_bg = "#1D1F21"
